import { ESTILOS, SEVERIDAD_PALABRA } from "@/lib/status"
import { formatearFechaHora, type Alerta, type Severidad } from "@/lib/mock-data"
import type { IndicadorTablero, LineaDemoConocida } from "@/lib/domain/floor-repository"

/**
 * G6: pure shift-report builder ("reporte de turno"), sent after a
 * back-office "Simular turno" when the toggle is ON (default). Kept out of
 * the mailer/route so it stays plain-Vitest testable, same pattern as
 * `lib/domain/simular-turno.ts`.
 */
export type ReporteTurnoInput = {
  linea: LineaDemoConocida
  /** Epoch ms; also the report's subject-line timestamp. */
  fecha: number
  /** Alerts generated by this shift (may be empty). */
  nuevasAlertas: readonly Alerta[]
  /** KPI states on the line AFTER the shift. */
  indicadores: readonly IndicadorTablero[]
  /** Total open (active) alerts on the line after the shift. */
  alertasAbiertas: number
  /** Base URL for the "ver el tablero" link, e.g. https://.../ (no trailing
   * "/planta" -- this builder appends it). */
  appBaseUrl: string
}

export type ReporteEmail = { subject: string; html: string; text: string }

// D8-style order: most severe first.
const ORDEN_SEVERIDAD: Severidad[] = ["parar", "atencion", "ok"]

export function construirReporteTurno(input: ReporteTurnoInput): ReporteEmail {
  const { linea, fecha, nuevasAlertas, indicadores, alertasAbiertas, appBaseUrl } = input
  const enlace = `${appBaseUrl.replace(/\/$/, "")}/planta`
  const subject = `Reporte de turno — ${linea} — ${formatearFechaHora(fecha)}`

  const grupos = ORDEN_SEVERIDAD.map((severidad) => ({
    palabra: SEVERIDAD_PALABRA[severidad],
    alertas: nuevasAlertas.filter((a) => a.severidad === severidad),
  })).filter((g) => g.alertas.length > 0)

  const textoAlertas =
    grupos.length === 0
      ? "Sin alertas nuevas en este turno."
      : grupos
          .map((g) => `${g.palabra} (${g.alertas.length}): ${g.alertas.map((a) => a.titulo).join(", ")}`)
          .join("\n")

  const htmlAlertas =
    grupos.length === 0
      ? "<p>Sin alertas nuevas en este turno.</p>"
      : `<ul>${grupos
          .map(
            (g) =>
              `<li><strong>${g.palabra}</strong> (${g.alertas.length}): ${g.alertas
                .map((a) => escapeHtml(a.titulo))
                .join(", ")}</li>`,
          )
          .join("")}</ul>`

  const textoIndicadores = indicadores.map((i) => `${i.nombre}: ${ESTILOS[i.estado].palabra}`).join("\n")
  const htmlIndicadores = `<ul>${indicadores
    .map((i) => `<li>${escapeHtml(i.nombre)}: <strong>${ESTILOS[i.estado].palabra}</strong></li>`)
    .join("")}</ul>`

  const text = [
    `Reporte de turno — ${linea}`,
    formatearFechaHora(fecha),
    "",
    "Alertas nuevas de este turno:",
    textoAlertas,
    "",
    "Estado de los indicadores tras el turno:",
    textoIndicadores,
    "",
    `Alertas abiertas en total: ${alertasAbiertas}`,
    "",
    `Ver el tablero: ${enlace}`,
  ].join("\n")

  const html = `
    <div>
      <h2>Reporte de turno — ${escapeHtml(linea)}</h2>
      <p>${escapeHtml(formatearFechaHora(fecha))}</p>
      <h3>Alertas nuevas de este turno</h3>
      ${htmlAlertas}
      <h3>Estado de los indicadores tras el turno</h3>
      ${htmlIndicadores}
      <p><strong>Alertas abiertas en total:</strong> ${alertasAbiertas}</p>
      <p><a href="${enlace}">Ver el tablero</a></p>
    </div>
  `.trim()

  return { subject, html, text }
}

function escapeHtml(value: string): string {
  return value
    .replaceAll("&", "&amp;")
    .replaceAll("<", "&lt;")
    .replaceAll(">", "&gt;")
    .replaceAll('"', "&quot;")
}
